2024-11-14 16:30:10,051 DEBUG    root            Loaded Command Group: ['gcloud', 'version']
2024-11-14 16:30:10,051 DEBUG    root            Running [gcloud.version] with arguments: [--format: "json"]
2024-11-14 16:30:10,113 DEBUG    root            Chosen display Format:flattened[no-pad,separator=" "] json
2024-11-14 16:30:10,113 INFO     root            Display format: "flattened[no-pad,separator=" "] json"
2024-11-14 16:30:10,230 INFO     ___FILE_ONLY___ {
  "Google Cloud SDK": "501.0.0",
  "core": "2024.11.08"
}
2024-11-14 16:30:10,230 INFO     ___FILE_ONLY___ 

2024-11-14 16:30:10,230 DEBUG    root            [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/Users/wbrunson/Library/Application Support/cloud-code/installer/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 998, in Execute
    resources = calliope_command.Run(cli=self, args=args)
  File "/Users/wbrunson/Library/Application Support/cloud-code/installer/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 843, in Run
    resources = display.Displayer(command_instance, args, resources,
  File "/Users/wbrunson/Library/Application Support/cloud-code/installer/google-cloud-sdk/lib/googlecloudsdk/calliope/display.py", line 495, in Display
    log.out.flush()
  File "/Users/wbrunson/Library/Application Support/cloud-code/installer/google-cloud-sdk/lib/googlecloudsdk/core/log.py", line 247, in flush
    self.__stream_wrapper.stream.flush()
BrokenPipeError: [Errno 32] Broken pipe
2024-11-14 16:30:10,262 DEBUG    root            Metrics reporting process started...
